### ISSUE TITLE
Commit "Rewrite subprocess run (Python >= 3.5)" breaks passff-host for older versions

### ISSUE THREAD

**Issue by JanWelker** [passff/passff-host#14]
Commit ac4b33830ae8b3e0cc95236a1caad197ce1f74f8 breaks passff-host on all python versions that do not know subprocess.run. Everything under 3.5 which basically is what every OS provides. Would it make sense to create a Python 3.5 branch for this?

Python Versions:
Ubuntu 17.10: 2.7.14
Fedora 27: 2.7.13
macOS: 2.6.1

**Comment by 5bentz** [comment]
Yes, this commit breaks the compatibility with Python3 versions older than 3.5.

Python 3.5 is the stable version now for **Python3** and has been released in late 2015.
The versions you mention are for **Python2** which is basically another language.

> Everything under 3.5 which basically is what every OS provides. 
Could you elaborate on that?
Have you a specific issue with the passff-host application?

* In the current Ubuntu releases, only Trusty (14.04) does not support Python3.5. See https://packages.ubuntu.com/search?keywords=python3&searchon=names&suite=all&section=all
* Fedora: Supports 3.5 since Fedora 26 at least https://apps.fedoraproject.org/packages/python3
* MacOS: Supports 3.5 through homebrew http://formulae.brew.sh/formula/python
* Even Debian Supports 3.5 since Stretch released in June 2017. https://packages.debian.org/search?keywords=python3&searchon=names&suite=all&section=all

Not to mention PassFF does not *officially* support Firefox 52 ESR which is still maintained and which has been released one year ago. Actually, PassFF still works wonder on FF ESR.

@tuxor1337 We could add a notice in the doc that the host app depends on Python3.

**Comment by tuxor1337** [comment]
@5bentz Thanks a lot for pointing this out! It's definitely a good idea to mention this in the README. Would you make the necessary changes, please? I invited you to become a member of PassFF which would give you write access to our repositories.

**Comment by tuxor1337** [comment]
Yes, of course. Whenever you need feedback, use PRs. But don't hesitate to push small changes directly - this would help me a lot already.

**Comment by 5bentz** [comment]
To clarify: before ac4b338, passff was already NOT compatible with Python 2.7 or 2.6 on ubuntu, fedora and macOS. So, without additional information, this issue is invalid for now. 

Please let me know if you have any questions.
