### ISSUE TITLE
Versioning scheme: Difference between passff 1.0.1 in git and releases

### ISSUE THREAD

**Issue by lanodan** [passff/passff-host#18]
It looks like you are rewriting releases as it looks like the [changes done in the meantime](https://github.com/passff/passff-host/compare/1.0.1...master#diff-17456ad518205ff2c062efdb0e7cb998), don’t do that, do a new release instead. (see https://semver.org/ ).

Basically it means that for packaging I’m using https://github.com/passff/passff-host/raw/1.0.1/src/passff.py with modifying ``_VERSIONHOLDER_`` instead.

```
$ wget https://github.com/passff/passff-host/releases/download/1.0.1/passff.py -O passff-host-1.0.1.py
$ wget https://github.com/passff/passff-host/raw/1.0.1/src/passff.py
$ diff -u passff.py passff-host-1.0.1.py
--- passff.py	2018-05-15 03:25:15.183654941 +0200
+++ passff-host-1.0.1.py	2018-04-04 19:34:17.000000000 +0200
@@ -7,21 +7,18 @@
 
 import os, sys, json, struct, subprocess
 
-VERSION = "_VERSIONHOLDER_"
+VERSION = "1.0.1"
 
 ################################################################################
 ######################## Begin preferences section #############################
 ################################################################################
-# Default command for MacOS:
-#command = "/usr/local/bin/pass"
-command     = "/usr/bin/pass"
-commandArgs = []
-commandEnv  = {
+COMMAND      = "pass"
+COMMAND_ARGS = []
+COMMAND_ENV  = {
     "TREE_CHARSET": "ISO-8859-1",
-    # Default PATH for MacOS:
-    #"PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
+    "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
 }
-charset     = "UTF-8"
+CHARSET      = "UTF-8"
 ################################################################################
 ######################### End preferences section ##############################
 ################################################################################
@@ -52,14 +49,14 @@
     receivedMessage = getMessage()
     opt_args = []
     pos_args = []
-    stdin = None
+    std_input = None
 
     if len(receivedMessage) == 0:
         pass
     elif receivedMessage[0] == "insert":
         opt_args = ["insert", "-m"]
         pos_args = [receivedMessage[1]]
-        stdin = receivedMessage[2]
+        std_input = receivedMessage[2]
     elif receivedMessage[0] == "generate":
         pos_args = [receivedMessage[1], receivedMessage[2]]
         opt_args = ["generate"]
@@ -69,37 +66,31 @@
         key = receivedMessage[0]
         key = "/" + (key[1:] if key[0] == "/" else key)
         pos_args = [key]
-    opt_args += commandArgs
+    opt_args += COMMAND_ARGS
 
     # Set up (modified) command environment
     env = dict(os.environ)
     if "HOME" not in env:
         env["HOME"] = os.path.expanduser('~')
-    for key, val in commandEnv.items():
+    for key, val in COMMAND_ENV.items():
         env[key] = val
 
     # Set up subprocess params
-    cmd = [command] + opt_args + ['--'] + pos_args
+    cmd = [COMMAND] + opt_args + ['--'] + pos_args
     proc_params = {
+        'input': bytes(std_input, CHARSET) if std_input else None,
         'stdout': subprocess.PIPE,
         'stderr': subprocess.PIPE,
         'env': env
     }
-    if 'stdin' is not None:
-      proc_params['stdin'] = subprocess.PIPE
 
     # Run and communicate with pass script
-    proc = subprocess.Popen(cmd, **proc_params)
-    if stdin is not None:
-      proc_in = bytes(stdin, charset)
-      proc_out, proc_err = proc.communicate(input=proc_in)
-    else:
-      proc_out, proc_err = proc.communicate()
+    proc = subprocess.run(cmd, **proc_params)
 
     # Send response
     sendMessage(encodeMessage({
         "exitCode": proc.returncode,
-        "stdout": proc_out.decode(charset),
-        "stderr": proc_err.decode(charset),
+        "stdout": proc.stdout.decode(CHARSET),
+        "stderr": proc.stderr.decode(CHARSET),
         "version": VERSION
     }))

```

**Comment by 5bentz** [comment]
Thumbs up & Good timing! I was about to post an issue about that in a few days/weeks.

Yes, it [happened](https://github.com/passff/passff/issues/323) that we re-released the 1.0.1 with a bugfix...because PassFF checks the host version like this: `if passff-host !== 1.0.1 then throw exception`, which is really wrong because...you know the answer.

To solve this issue, we should definitely enforce Semantic versioning (or [explicit versioning](https://github.com/exadra37-versioning/explicit-versioning)) for passff-host, ie:
- Use a versioning schema *A.B.C*, or *major.minor.path* where
  - C is incremented when bugfix
  - B is incremented when new feature
  - A is incremented when incompatibility (in the API) is introduced

so that PassFF can simply checks: `if passff-host !== 1.x.y then throw exception` (where x and y can be any non-negative integers), or `passff-host >= 1.0 and passff-host < 2.0` 

I'm mixed about it but I'd also suggest that PassFF follows SemVer regarding Firefox's extension API. For example:
* The move from XUL to webext would have been an incrementation of the major version (0.x.y -> 1.0.0).
* Let's say PassFF requires a new feature of Firefox version FooBar, thus breaking the compatibility with previous versions. This change would also increment the major version.

**Comment by lanodan** [comment]
> Let's say PassFF requires a new feature of Firefox version FooBar, thus breaking the compatibility with previous versions. This change would also increment the major version.

Yes, it would. For it to be a minor increment it would be adding a new feature/API-dependency but without break (``try…catch``, feature check, …).

Anyway, I used SemVer as an example of a versioning scheme that makes sense, from what I see Explicit Versioning just adds another level on top of Major, Disruptive.

**Comment by 5bentz** [comment]
@tuxor1337 What do you think?

Such improvement seems threefold:
* Enforcing whatever versioning (semantic, explicit, etc) and stick with it
* Modify/Implement version checks in passff and passff-host
* Document it for future maintainers, devs, package managers and users

**Comment by tuxor1337** [comment]
Yes, semantic versioning sounds cool to me. The version checks in the extension have to be modified accordingly. If you really think it's necessary, somebody would have to implement version checks in the host app, as well. Personally, I won't put any time into an implementation in the next weeks, but I will be happy to check pull requests if somebody comes up with an implementation.

**Comment by 5bentz** [comment]
> If you really think it's necessary, somebody would have to implement version checks in the host app, as well

Why? Could you elaborate?

To me, the host app provides a public API that can be used by any tool [1]. The tool has to make sure it is compatible with the version of passff-host. In terms of dependency, passff depends on passff-host, not the opposite.

Am I misguided?

On a side note, passff-host could check the version of `pass` (or `python` 2 or 3, which might be more relevant...).

[1] In practice, only passff needs passff-host of course. But who knows... :3

**Comment by lanodan** [comment]
@tuxor1337 
I also quite fail to see what version check would have to be done in the host app. If you meant passff-host checking on passff, I think it’s quite a bad idea as passff-host doesn’t depend on passff and it would probably mean some release will happen only for version bumping.

---

@5bentz 
I fail to see why the version of pass should be checked. AFAIK it’s API very stable.
Also AFAIK passff-host only works with python 3.4+ (3.5+ for git) and this one is probably already done by setup.py and other packaging tools. (It is for gentoo ebuilds)

**Comment by 5bentz** [comment]
@lanodan 
Since pass-host depends on pass, we *could* add a version check. Is it relevant? Nope of course ;)
Yes, passff-host requires Python 3.5 now, which is installed on most (if not all) distros for several years. A check would be a waste of time. See https://github.com/passff/passff-host/issues/14

**Comment by tuxor1337** [comment]
@5bentz wrote:
> Modify/Implement version checks in passff and passff-host
This is what I was refering to. I don't see any reason why you would want to have version checks in passff-host. But it was @5bentz's suggestion, so I leave it up to him to decide.

**Comment by 5bentz** [comment]
Wouaw I'm confused. I guess I meant: "Check current version checks in passff (passff and passff-host) and modify them accordingly". Sorry :o 

After finishing my polish of the documentation, I will tackle this implementation :+1:

**Comment by 5bentz** [comment]
In https://semver.org/, we have to define the *public API*. 

I'm doing my own reasoning below. Comment and challenge my proposition :hammer: 

## “If I were a user/package maintainer, what do I care about?”

### In PassFF-host
* As a user of passff-host (eg. PassFF uses PassFF-host), I care about the input/output of PassFF-host.
* As a package maintainer (eg. Gentoo/Arch pkgs), I care about semver, dependencies, and about the various install scripts.
* As an end-user, I care about install scripts.

#### Use Cases
* Bugfix, security fix in passff.py -> patch++
* Bugfix in install script -> patch++
* New install script -> minor++
* Additional field returned by passff.py -> minor++
* Additional way to interact with passff.py (eg. `echo 'generate passname 12' | passff.py`) -> minor++
* Incompatible input/output changes in passff.py -> major++

### In PassFF
* As a user of PassFF, I care about PassFF running in my current browser
* I also care about the GUI: its design, its features
 * As a package maintainer, I care about semver & dependencies.

#### Use Cases
* Bugfix, security fix -> patch++
* Translation update & typos -> patch++
* GUI redesign -> patch++ or minor++ *it depends on the changes (scale, impact)*
* New language -> minor++
* New features -> minor++
* Usage of a new feature from webext/firefox's API
  * If break compatibility with older browsers -> major++
  * Otherwise -> minor++

Finally, we (try to) do not change dependencies to annoy package managers. They are consequences or other changes: new features or rewrites.

**Comment by lanodan** [comment]
> In https://semver.org/, we have to define the public API.

Pretty sure you can avoid it a bit, but documentation is always nice. The “Public API” thing of semver.org could be replaced to “(documented) Inter-Process API/User Interface”.

## Use Cases
> * Incompatible input/output changes in passff.py -> major++

Also consider bumping major if the install script arguments changes.

**Comment by tuxor1337** [comment]
Cool, thanks :+1: What does that mean for the next release version of PassFF?

**Comment by lanodan** [comment]
> Thus the next release will be **1.4**.

This is about PassFF right, what about PassFF-host? You should probably bump passff-host too so releases would have the correct tags linked to them.
So just to be sure I think both should keep their own versions, so one can be updated without bumping the other.

**Comment by tuxor1337** [comment]
Version 1.4 is available from AMO now.

@5bentz We could bump the host app to 1.1 or 1.0.2 or something to have a clean correct version for packagers as suggested by @lanodan - what do you think?

**Comment by 5bentz** [comment]
Of course, the `1.0.2` draft release has been made 10 days ago. Feel free to review and publish it ;)

For 1.1, we have the Cygwin install script, but it is not ready yet.

**Comment by tuxor1337** [comment]
Okay, closing as fixed.
